Declare @condition_id int
EXEC msdb.dbo.sp_syspolicy_add_condition @name=N'Check database settings', @description=N'', @facet=N'Database', @expression=N'<Operator>
  <TypeClass>Bool</TypeClass>
  <OpType>AND</OpType>
  <Count>2</Count>
  <Operator>
    <TypeClass>Bool</TypeClass>
    <OpType>AND</OpType>
    <Count>2</Count>
    <Operator>
      <TypeClass>Bool</TypeClass>
      <OpType>AND</OpType>
      <Count>2</Count>
      <Operator>
        <TypeClass>Bool</TypeClass>
        <OpType>AND</OpType>
        <Count>2</Count>
        <Operator>
          <TypeClass>Bool</TypeClass>
          <OpType>AND</OpType>
          <Count>2</Count>
          <Operator>
            <TypeClass>Bool</TypeClass>
            <OpType>AND</OpType>
            <Count>2</Count>
            <Operator>
              <TypeClass>Bool</TypeClass>
              <OpType>AND</OpType>
              <Count>2</Count>
              <Operator>
                <TypeClass>Bool</TypeClass>
                <OpType>AND</OpType>
                <Count>2</Count>
                <Operator>
                  <TypeClass>Bool</TypeClass>
                  <OpType>EQ</OpType>
                  <Count>2</Count>
                  <Attribute>
                    <TypeClass>Bool</TypeClass>
                    <Name>AutoCreateIncrementalStatisticsEnabled</Name>
                  </Attribute>
                  <Function>
                    <TypeClass>Bool</TypeClass>
                    <FunctionType>True</FunctionType>
                    <ReturnType>Bool</ReturnType>
                    <Count>0</Count>
                  </Function>
                </Operator>
                <Operator>
                  <TypeClass>Bool</TypeClass>
                  <OpType>EQ</OpType>
                  <Count>2</Count>
                  <Attribute>
                    <TypeClass>Bool</TypeClass>
                    <Name>AutoCreateStatisticsEnabled</Name>
                  </Attribute>
                  <Function>
                    <TypeClass>Bool</TypeClass>
                    <FunctionType>True</FunctionType>
                    <ReturnType>Bool</ReturnType>
                    <Count>0</Count>
                  </Function>
                </Operator>
              </Operator>
              <Operator>
                <TypeClass>Bool</TypeClass>
                <OpType>EQ</OpType>
                <Count>2</Count>
                <Attribute>
                  <TypeClass>Bool</TypeClass>
                  <Name>AutoUpdateStatisticsAsync</Name>
                </Attribute>
                <Function>
                  <TypeClass>Bool</TypeClass>
                  <FunctionType>True</FunctionType>
                  <ReturnType>Bool</ReturnType>
                  <Count>0</Count>
                </Function>
              </Operator>
            </Operator>
            <Operator>
              <TypeClass>Bool</TypeClass>
              <OpType>EQ</OpType>
              <Count>2</Count>
              <Attribute>
                <TypeClass>Bool</TypeClass>
                <Name>AutoUpdateStatisticsEnabled</Name>
              </Attribute>
              <Function>
                <TypeClass>Bool</TypeClass>
                <FunctionType>True</FunctionType>
                <ReturnType>Bool</ReturnType>
                <Count>0</Count>
              </Function>
            </Operator>
          </Operator>
          <Operator>
            <TypeClass>Bool</TypeClass>
            <OpType>EQ</OpType>
            <Count>2</Count>
            <Attribute>
              <TypeClass>Bool</TypeClass>
              <Name>BrokerEnabled</Name>
            </Attribute>
            <Function>
              <TypeClass>Bool</TypeClass>
              <FunctionType>False</FunctionType>
              <ReturnType>Bool</ReturnType>
              <Count>0</Count>
            </Function>
          </Operator>
        </Operator>
        <Operator>
          <TypeClass>Bool</TypeClass>
          <OpType>EQ</OpType>
          <Count>2</Count>
          <Attribute>
            <TypeClass>Numeric</TypeClass>
            <Name>CompatibilityLevel</Name>
          </Attribute>
          <Function>
            <TypeClass>Numeric</TypeClass>
            <FunctionType>Enum</FunctionType>
            <ReturnType>Numeric</ReturnType>
            <Count>2</Count>
            <Constant>
              <TypeClass>String</TypeClass>
              <ObjType>System.String</ObjType>
              <Value>Microsoft.SqlServer.Management.Smo.CompatibilityLevel</Value>
            </Constant>
            <Constant>
              <TypeClass>String</TypeClass>
              <ObjType>System.String</ObjType>
              <Value>Version150</Value>
            </Constant>
          </Function>
        </Operator>
      </Operator>
      <Operator>
        <TypeClass>Bool</TypeClass>
        <OpType>NE</OpType>
        <Count>2</Count>
        <Attribute>
          <TypeClass>Numeric</TypeClass>
          <Name>DelayedDurability</Name>
        </Attribute>
        <Function>
          <TypeClass>Numeric</TypeClass>
          <FunctionType>Enum</FunctionType>
          <ReturnType>Numeric</ReturnType>
          <Count>2</Count>
          <Constant>
            <TypeClass>String</TypeClass>
            <ObjType>System.String</ObjType>
            <Value>Microsoft.SqlServer.Management.Smo.DelayedDurability</Value>
          </Constant>
          <Constant>
            <TypeClass>String</TypeClass>
            <ObjType>System.String</ObjType>
            <Value>Disabled</Value>
          </Constant>
        </Function>
      </Operator>
    </Operator>
    <Operator>
      <TypeClass>Bool</TypeClass>
      <OpType>EQ</OpType>
      <Count>2</Count>
      <Attribute>
        <TypeClass>Numeric</TypeClass>
        <Name>PageVerify</Name>
      </Attribute>
      <Function>
        <TypeClass>Numeric</TypeClass>
        <FunctionType>Enum</FunctionType>
        <ReturnType>Numeric</ReturnType>
        <Count>2</Count>
        <Constant>
          <TypeClass>String</TypeClass>
          <ObjType>System.String</ObjType>
          <Value>Microsoft.SqlServer.Management.Smo.PageVerify</Value>
        </Constant>
        <Constant>
          <TypeClass>String</TypeClass>
          <ObjType>System.String</ObjType>
          <Value>Checksum</Value>
        </Constant>
      </Function>
    </Operator>
  </Operator>
  <Operator>
    <TypeClass>Bool</TypeClass>
    <OpType>EQ</OpType>
    <Count>2</Count>
    <Attribute>
      <TypeClass>Numeric</TypeClass>
      <Name>ParameterSniffing</Name>
    </Attribute>
    <Function>
      <TypeClass>Numeric</TypeClass>
      <FunctionType>Enum</FunctionType>
      <ReturnType>Numeric</ReturnType>
      <Count>2</Count>
      <Constant>
        <TypeClass>String</TypeClass>
        <ObjType>System.String</ObjType>
        <Value>Microsoft.SqlServer.Management.Smo.DatabaseScopedConfigurationOnOff</Value>
      </Constant>
      <Constant>
        <TypeClass>String</TypeClass>
        <ObjType>System.String</ObjType>
        <Value>On</Value>
      </Constant>
    </Function>
  </Operator>
</Operator>', @is_name_condition=0, @obj_name=N'', @condition_id=@condition_id OUTPUT
Select @condition_id

GO

